// This file will be generated by Supabase CLI
// For now, we'll use a basic type definition
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          role: 'owner' | 'admin' | 'employee';
          category: string | null;
          store_name: string | null;
          id_store: string | null;
          email: string;
          phone: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          role?: 'owner' | 'admin' | 'employee';
          category?: string | null;
          store_name?: string | null;
          id_store?: string | null;
          email: string;
          phone?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          role?: 'owner' | 'admin' | 'employee';
          category?: string | null;
          store_name?: string | null;
          id_store?: string | null;
          email?: string;
          phone?: string | null;
          created_at?: string;
        };
      };
      stores: {
        Row: {
          id: string;
          address: string;
          reviews: number | null;
          photos: string[] | null;
          store_name: string;
          title: string;
          work_days: any;
          categories: string[];
          blocked_dates: string[];
          whitelist: string[];
          theme_colors: any | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          address: string;
          reviews?: number | null;
          photos?: string[] | null;
          store_name: string;
          title: string;
          work_days: any;
          categories: string[];
          blocked_dates?: string[];
          whitelist?: string[];
          theme_colors?: any | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          address?: string;
          reviews?: number | null;
          photos?: string[] | null;
          store_name?: string;
          title?: string;
          work_days?: any;
          categories?: string[];
          blocked_dates?: string[];
          whitelist?: string[];
          theme_colors?: any | null;
          created_at?: string;
        };
      };
      services: {
        Row: {
          id: string;
          id_store: string;
          index: number;
          service_name: string;
          duration: number;
          price: number;
          description: string | null;
          profession: string;
          category: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          id_store: string;
          index: number;
          service_name: string;
          duration: number;
          price: number;
          description?: string | null;
          profession: string;
          category: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          id_store?: string;
          index?: number;
          service_name?: string;
          duration?: number;
          price?: number;
          description?: string | null;
          profession?: string;
          category?: string;
          created_at?: string;
        };
      };
      reservations: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string;
          note: string | null;
          date_time: string;
          service_duration: number;
          service_name: string;
          id_store: string;
          employee: string | null;
          profession: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone: string;
          note?: string | null;
          date_time: string;
          service_duration: number;
          service_name: string;
          id_store: string;
          employee?: string | null;
          profession: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string;
          note?: string | null;
          date_time?: string;
          service_duration?: number;
          service_name?: string;
          id_store?: string;
          employee?: string | null;
          profession?: string;
          created_at?: string;
        };
      };
    };
  };
};
